//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOrderProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailNotification
    {
        public int Id { get; set; }
        public string UserCode { get; set; }
        public string OrderCode { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> MailDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
