//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOrderProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int id { get; set; }
        public Nullable<int> Line { get; set; }
        public string Orderno { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> TotalPirice { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Image { get; set; }
        public Nullable<double> StockKeepingUnit { get; set; }
        public string barcode { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
